baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Alpha Programming'

paginate = 2

[params]
  description = "Alpha Programming by Xavier Elon"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
