baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Alpha Programming'
favicon = true

paginate = 5

[params]
  description = "Alpha Programming by Xavier Elon"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
